apiVersion: redhatgov.io/v1alpha1
kind: Nexus
metadata:
  name: nexus
spec:
  nexus:
    oauth:
      adminUsers:
        - user1
        - user2
        - user3
        - user4
        - user5
        - bdumont
